version:  '3'
services:
    # sonarqube:
    #     container_name:  sonarqube
    #     image:  sonarqube:latest
    #     ports:
    #         -  "9000:9000"
    #         -  "9092:9092"
    # frontend:
    # backend:
    #     image: pm2graphql
    #     container_name: pm2graphql
    db:
        image: postgres
        restart: always
        container_name: db
        environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=database
        ports:
        - 5432:5432
        volumes:
        - postgres:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080