apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    name: frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm2graphql
spec:
  selector:
    matchLabels:
      name: pm2graphql
  template:
    metadata:
      labels:
        name: pm2graphql
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: pm2graphql
        image: noname001/pm2graphql
        env:
        - name: DB_HOST
          value: postgres://db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: db
        image: noname001/db
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    name: db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pm2graphql
spec:
  selector:
    name: pm2graphql
  ports:
  - port: 4000
    targetPort: 4000
